name: CI
on: [push]
jobs:
  build:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Create mongo Docker container
        id: build_mongo_docker
        uses: DigiPie/mongo-action@v1.0.0
        with:
          image-version: latest
          port: 27017
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm install
      - run: npm test
